language: go
sudo: false
go:
  - 1.9.5
  - "1.10.1"
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
env:
  - DEP_VERSION="0.4.1"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure
script:
  - go test
