language: go
sudo: false
go:
  - 1.9.5
  - "1.10.1"
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get -u github.com/golang/dep
  - dep ensure
script:
  - go test
